# yaml-language-server: $schema=https://raw.githubusercontent.com/mattn/efm-langserver/master/schema.json

version: 2
lint-debounce: 1s
format-debounce: 0.5s

root-markers:
  - .git/

tools:
  any-typos: &any-typos
    lint-source: typos
    lint-debounce: 3s
    lint-command: "typos - --format brief"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-severity: 3
    lint-formats:
      - "-:%l:%c: %m"

  markdown-markdownlint: &markdown-markdownlint
    lint-source: markdownlint
    lint-severity: 2
    lint-command: "markdownlint -s"
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"
      - "%f:%l:%c %m"
      - "%f: %l: %m"

  dockerfile-hadolint: &dockerfile-hadolint
    lint-source: hadolint
    lint-command: "hadolint --no-color -"
    lint-stdin: true
    lint-formats:
      - "%f:%l DL%n %t%.%#: %m"

languages:
  =:
    - <<: *any-typos
  markdown:
    - <<: *markdown-markdownlint
  dockerfile:
    - <<: *dockerfile-hadolint
