gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - underline
  showDivergenceFromBaseBranch: arrowAndNumber
  expandFocusedSidePanel: true

customCommands:
  - key: "<c-space>"
    command: "gitmoji -c"
    context: "files"
    description: "Commit changes with gitmoji"
    subprocess: true

git:
  commit:
    autoWrapCommitMessage: false
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  branchLogCmd: "git log \
    --graph \
    --color=always \
    --abbrev-commit \
    --decorate \
    --date=iso-strict \
    --pretty=format:\"%C(auto)%H %d%nAuthor(%ad): %an <%ae>%nCommit(%cd): %cn <%ce>%n%n%w(0,4,4)%B%n\" \
    {{branchName}} --"
  overrideGpg: true

promptToReturnFromSubprocess: false

os:
  editPreset: "nvim-remote"
