gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - underline
  showDivergenceFromBaseBranch: arrowAndNumber
  expandFocusedSidePanel: true

customCommands:
  - key: "<c-space>"
    command: "gitmoji -c"
    context: "files"
    description: "Commit changes with gitmoji"
    subprocess: true

git:
  commit:
    autoWrapCommitMessage: false
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  overrideGpg: true
