"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
  { on = ["<Enter>"], run = "enter", desc = "Enter the child directory" },
  { on = ["Q"], run = ["quit"], desc = "Exit and Change Directory" },
  { on = ["q"], run = "quit --no-cwd-file", desc = "Exit the process without writing cwd-file" },
  { on = ["<PageUp>"], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = ["<PageDown>"], run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = ["g", "?"], run = "help", desc = "Open help" },
]

[select]
prepend_keymap = []

[input]
prepend_keymap = [
  { on = ["<Esc>"], run = "close", desc = "Cancel input" },
]
