"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = ["Q"], run = ["quit"], desc = "Exit and Change Directory" },
  { on = ["q"], run = "quit --no-cwd-file", desc = "Exit the process without writing cwd-file" },
  { on = ["<PageUp>"], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = ["<PageDown>"], run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = ["g", "?"], run = "help", desc = "Open help" },
  { on = ["g", "t"], run = "cd ~/Desktop", desc = "Goto Desktop" },
  { on = ["f"], run = "plugin jump-to-char", desc = "Jump to char" },
  { on = ["F"], run = "filter", desc = "Filter" },
  { on = ["T"], run = "plugin toggle-pane max-preview", desc = "Change preview size" },
]

[input]
prepend_keymap = [
  { on = ["<Esc>"], run = "close", desc = "Cancel input" },
]
