"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
sort_dir_first = true
show_hidden = true
linemode = "size"

[preview]
wrap = "yes"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[plugin.append_previewers]]
name = "*"
run = 'piper -- hexyl --border=none --terminal-width=$w "$1"'
