[settings]
mouse_mode = true

[keybindings.Menu]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Ctrl-1>" = "FocusMenu"
"<Ctrl-2>" = "FocusEditor"
"<Ctrl-3>" = "FocusData"
"<Ctrl-4>" = "FocusHistory"
"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.Editor]
"<Ctrl-q>" = "AbortQuery"
"<Ctrl-s>" = "SubmitEditorQuery"
"<Ctrl-1>" = "FocusMenu"
"<Ctrl-2>" = "FocusEditor"
"<Ctrl-3>" = "FocusData"
"<Ctrl-4>" = "FocusHistory"
"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.History]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Ctrl-1>" = "FocusMenu"
"<Ctrl-2>" = "FocusEditor"
"<Ctrl-3>" = "FocusData"
"<Ctrl-4>" = "FocusHistory"
"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.Data]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Ctrl-1>" = "FocusMenu"
"<Ctrl-2>" = "FocusEditor"
"<Ctrl-3>" = "FocusData"
"<Ctrl-4>" = "FocusHistory"
"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.PopUp]
"<Ctrl-c>" = "Quit"
