#!/bin/sh
set -o errexit -o nounset -o pipefail

GIT_ROOT=$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)
LOCAL_HOOK="${GIT_ROOT}/hooks/pre-commit"

if [ -f "$LOCAL_HOOK" ]; then
  echo "[INFO: pre-commit] Run Local Hook"
  "$LOCAL_HOOK"
fi

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
if [ -z "$FILES" ]; then
  echo "[INFO: pre-commit] SKIPPED: No Diff"
  exit 0
fi

echo "[INFO: pre-commit] Run secretlint"
echo "$FILES" | xargs secretlint --secretlintrc "${XDG_CONFIG_HOME}/secretlint/.secretlintrc.json"
